unique_ids:
  assets:
    standard-page.html: OIUWSQCYSMF4HJYVYK7SYIMSSM6IUJZP
    theme.css: NZDM7LOJGRUF5EUTQZSLZR5HWL47UZ2Q
  forms:
    Form1: REWOZABJHL4XYMM2NIWTT5WEKOYCWMAL
  modules: {}
  scripts: {}
  server_modules: {}
